source 'https://rubygems.org'

group :integration do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'kitchen-docker'
  gem 'kitchen-openstack'
end

gem 'librarian-chef', '~> 0.0.4'
gem 'foodcritic', '~> 4.0'
gem 'chefspec', '~> 4.2'
gem 'chef', '~> 12.1'
gem 'finstyle'
gem 'guard-rubocop'
gem 'guard-rspec'
gem 'guard-foodcritic'
